/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-01-31 09:54:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1485738599553L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction goSubmit() {\r\n");
      out.write("\t\tvar url = \"register/firm.do\";\r\n");
      out.write("\t\tvar formId = \"loginForm\";\r\n");
      out.write("\t\tajaxSumbit(url, formId);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#000\">\r\n");
      out.write("\t<div id=\"myCarousel\" class=\"carousel slide\" style=\"width:100%;height:382px;\">\r\n");
      out.write("\t    <!-- 轮播（Carousel）指标 -->\r\n");
      out.write("\t    <ol class=\"carousel-indicators\">\r\n");
      out.write("\t        <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t        <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t        <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t    </ol>   \r\n");
      out.write("\t    <!-- 轮播（Carousel）项目 -->\r\n");
      out.write("\t    <div class=\"carousel-inner\">\r\n");
      out.write("\t        <div class=\"item active\" style=\"height:382px;\">\r\n");
      out.write("\t            <img src=\"../img/banner1.png\">\r\n");
      out.write("\t\t\t\t<div style=\"width:480px;margin-top:-280px;margin-left:800px;z-index:9999;\">\r\n");
      out.write("\t            \t<table>\r\n");
      out.write("\t            \t\t<tr height=\"40px\">\r\n");
      out.write("\t            \t\t\t<td>\r\n");
      out.write("\t\t\t\t            \t<font color=\"#FFF\" size=\"5\">连接中高端人才，我们更懂业务</font>\r\n");
      out.write("\t            \t\t\t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t<tr height=\"40px\">\r\n");
      out.write("\t            \t\t\t<td>\r\n");
      out.write("\t\t\t\t            \t<font color=\"#FFF\">每周100+优质互联网人才等你邀请</font>\r\n");
      out.write("\t            \t\t\t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t<tr height=\"40px\">\r\n");
      out.write("\t            \t\t\t<td>\r\n");
      out.write("\t\t\t\t            \t<font color=\"#FFF\">Java、Web前端、iOS、android、UI设计、产品经理等火热应聘中</font>\r\n");
      out.write("\t            \t\t\t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t<tr height=\"40px\">\r\n");
      out.write("\t            \t\t\t<td>\r\n");
      out.write("\t\t\t\t            \t<button type=\"button\" class=\"btn btn-default\" style=\"width:150px\">免费注册</button>\r\n");
      out.write("\t            \t\t\t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t</table>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"item\">\r\n");
      out.write("\t            <img src=\"/wp-content/uploads/2014/07/slide2.png\" alt=\"Second slide\">\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t        <div class=\"item\">\r\n");
      out.write("\t            <img src=\"/wp-content/uploads/2014/07/slide3.png\" alt=\"Third slide\">\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <!-- 轮播（Carousel）导航 -->\r\n");
      out.write("\t    <a class=\"carousel-control left\" href=\"#myCarousel\" \r\n");
      out.write("\t        data-slide=\"prev\">&lsaquo;\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t    <a class=\"carousel-control right\" href=\"#myCarousel\" \r\n");
      out.write("\t        data-slide=\"next\">&rsaquo;\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"background-color:#FFF;height:300px;\">\r\n");
      out.write("\t\t<table class=\"textC\" width=\"100%\">\r\n");
      out.write("\t\t\t<tr height=\"60px\">\r\n");
      out.write("\t\t\t\t<td colspan=\"6\" class=\"textC\" height=\"20px\"><font size=\"4\" color=\"#777777\">一种全新招聘流程体验</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" height=\"100px\"><img src=\"../img/notebook.png\" width=\"70px\" height=\"70px\"/></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" height=\"100px\"><img src=\"../img/yearbook.png\" width=\"70px\" height=\"70px\"/></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" height=\"100px\"><img src=\"../img/paper_plane.png\" width=\"70px\" height=\"70px\"/></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" height=\"100px\"><img src=\"../img/anpaimianshi.png\" width=\"70px\" height=\"70px\"/></td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" style=\"height:40px\"><font size=\"3\" color=\"#777777\" style=\"font-weight:bold;\">1、开始推荐简历</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" style=\"height:40px\"><font size=\"3\" color=\"#777777\" style=\"font-weight:bold;\">2、挑选合适的候选人</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" style=\"height:40px\"><font size=\"3\" color=\"#777777\" style=\"font-weight:bold;\">3、发送面试邀请</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" style=\"height:40px\"><font size=\"3\" color=\"#777777\" style=\"font-weight:bold;\">4、安排面试</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" valign=\"top\"><font size=\"1\" color=\"#808080\" style=\"text-align:left\">我们每周会推荐一批<br/>大致符合贵公司招聘<br/>需求的全新候选人。</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" valign=\"top\"><font size=\"1\" color=\"#808080\" style=\"text-align:left\">通过职位、工作年限<br/>候选人项目经验、顾问<br/>综合评价等就可以从中<br/>筛选出满意的候选人。</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" valign=\"top\"><font size=\"1\" color=\"#808080\" style=\"text-align:left\">填写职位、薪资范围<br/>股权期权以及邀请信<br/>既可向候选人发送面试<br/>邀请。</font></td>\r\n");
      out.write("\t\t\t\t<td class=\"textC\" valign=\"top\"><font size=\"1\" color=\"#808080\" style=\"text-align:left\">候选人接收面试邀请<br/>之后，可以查看到TA<br/>的姓名及其联系方式，<br/>顾问会协助线下安排<br/>面试。</font></td>\r\n");
      out.write("\t\t\t\t<td width=\"15%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"height:300px;background-color:#E4E7E6;\">\r\n");
      out.write("\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t<tr height=\"50px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"4\" class=\"textC\"><font size=\"4\">u<font color=\"#00B38A\">o</font>ffer 帮你发现这样的人才</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"background-color:#FFF;height:600px;\">\r\n");
      out.write("\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t<tr height=\"50px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"5\" class=\"textC\"><font size=\"5\">u<font color=\"#00B38A\">o</font>ffer Q&A</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"30px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t\t<table style=\"font-size:1px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\"><img src=\"../img/Q.png\" width=\"30px\" height=\"30px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer是一个什么样</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">招聘网站？</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t\t<table style=\"font-size:1px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\"><img src=\"../img/Q.png\" width=\"30px\" height=\"30px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer与别的招聘网站</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">有何不同？</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"10px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\" style=\"background-color:#EEFFF5;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\">\r\n");
      out.write("\t\t\t\t\t\t<font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer</font>\r\n");
      out.write("\t\t\t\t\t\t是国内目前唯一一个可以高效批量接触到\r\n");
      out.write("\t\t\t\t\t\t优质互联网人才的网站，而且简历信息里包括\r\n");
      out.write("\t\t\t\t\t\t候选人的具体求职意向以及社交类网址，省去了\r\n");
      out.write("\t\t\t\t\t\tHR漫长的搜索优质候选人的过程,您可以集中精力\r\n");
      out.write("\t\t\t\t\t\t跟候选人沟通、面试、大大提升招聘效率。\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\" style=\"background-color:#EEFFF5;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\">\r\n");
      out.write("\t\t\t\t\t\t在<font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer</font>\r\n");
      out.write("\t\t\t\t\t\t您不需要撰写JD、发布职位，我们把所有的候选人直接展示在您的面前，\r\n");
      out.write("\t\t\t\t\t\t您只需要挑选出合适的候选人邀请他们过来面试既可，uoffer对每一位\r\n");
      out.write("\t\t\t\t\t\t候选人严格审核，确保只将最优秀的互联网人才被推荐，而在传统招聘网站\r\n");
      out.write("\t\t\t\t\t\t您只会收到大量参差不起的简历更有可能求职意向不明，严重影响您的工作效率。\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"60px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t\t<table style=\"font-size:1px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\"><img src=\"../img/Q.png\" width=\"30px\" height=\"30px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer提供怎样的</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">候选人？</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\">\r\n");
      out.write("\t\t\t\t\t<table style=\"font-size:1px;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\"><img src=\"../img/Q.png\" width=\"30px\" height=\"30px\"/></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer如何进行</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font style=\"font-weight:bold;\">收费？</font></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"10px\"/>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\" style=\"background-color:#EEFFF5;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\">\r\n");
      out.write("\t\t\t\t\t\t<font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer</font>\r\n");
      out.write("\t\t\t\t\t\t是一个中高端人才招聘网站，专注为互联网行业推荐中高端技术类、产品类、\r\n");
      out.write("\t\t\t\t\t\t设计类等职位人才，他们工作3年以上，近期有明确求职意向，平均年薪15w\r\n");
      out.write("\t\t\t\t\t\t以上，并通过我们顾问沟通后严格筛选出来的简历。\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\" style=\"background-color:#EEFFF5;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\">\r\n");
      out.write("\t\t\t\t\t\t<font style=\"font-weight:bold;\">U<font color=\"#00B38A\">o</font>ffer</font>\r\n");
      out.write("\t\t\t\t\t\t按招聘结果付费的形式收费，在uoffer注册账号、看简历、发面试邀请、\r\n");
      out.write("\t\t\t\t\t\t面试候选人都是不需要任何费用，只有在候选人成功入职后，我们才会收费，\r\n");
      out.write("\t\t\t\t\t\t且大部分人选我们只收取候选人一个月月薪，高端人才按年薪的比例佣金，\r\n");
      out.write("\t\t\t\t\t\t而且我们有三个月的保证期。\r\n");
      out.write("\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"20%\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
