/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-02-23 03:45:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class mainresume_005fadd_005finformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1486536911388L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar code;\r\n");
      out.write("\tfunction getTran(ret) {\r\n");
      out.write("\t\tvar trans1 = document.getElementById('transparent1');\r\n");
      out.write("\t\tvar trans2 = document.getElementById('transparent2');\r\n");
      out.write("\t\tif (ret == '1') {\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (ret == '2') {\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeRemeber() {\r\n");
      out.write("\t\tvar remeberId = document.getElementById('remeberId').value;\r\n");
      out.write("\t\tif (remeberId == '1') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/cha.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '2';\r\n");
      out.write("\t\t} else if (remeberId == '2') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/gou.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '1';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tgetTran('1');\r\n");
      out.write("\t\tvar regit = document.getElementById('regit');\r\n");
      out.write("\t\tregit.focus();\r\n");
      out.write("\t\tvar b = document.getElementById('button1');\r\n");
      out.write("\t\tb.focus();\r\n");
      out.write("\t\tcode = createValidateCode('vCode2');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validateCode() {\r\n");
      out.write("\t\tvar ispass = code.verify(document.getElementById(\"inputCode\").value);\r\n");
      out.write("\t\tif (ispass) {\r\n");
      out.write("\t\t\tvar url = \"saveUserInfo/user.do\";\r\n");
      out.write("\t\t\tvar formId = \"userInformationForm\";\r\n");
      out.write("\t\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\t\t$(\"#registerForm\").populateForm(data);\r\n");
      out.write("\t\t\twindow.location.href='mainlogin.jsp';\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"验证码输入有误！\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tgetTran('1');\r\n");
      out.write("\t\tvar regit = document.getElementById('regit');\r\n");
      out.write("\t\tregit.focus();\r\n");
      out.write("\t\tvar b = document.getElementById('button1');\r\n");
      out.write("\t\tb.focus();\r\n");
      out.write("\t\tcode2 = createValidateCode('vCode2');\r\n");
      out.write("\t\tvar url = \"jobList/user.do\";\r\n");
      out.write("\t\tvar formId = \"registerForm\";\r\n");
      out.write("\t\tvar data = ajaxSumbit(url, formId);\r\n");
      out.write("\t\t//$(\"#registerForm\").populateForm(data);\r\n");
      out.write("\t\tvar inn = \"\";\r\n");
      out.write("\t\tfor(var i in data){\r\n");
      out.write("\t\t\tinn = inn + \"<li role='presentation'>\"\r\n");
      out.write("\t\t\t\t+\"<a role='menuitem' onclick='jobValue(\" + data[i].id +\",\\\"\" + data[i].value +\"\\\")'><font color='#000'>\" + data[i].value\r\n");
      out.write("\t\t\t\t+\"</font></a></li>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.getElementById(\"nowjob\").innerHTML=inn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction setSexValue(id) {\r\n");
      out.write("\t\tif(id==1){\r\n");
      out.write("\t\t\t$(\"#offerUserSex\").val(\"男\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#offerUserSex\").val(\"女\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talert($(\"#offerUserSex\").val());\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#999999\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#000\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jobId(job){\r\n");
      out.write("\t\tif(job.getAttribute('class') == \"icheckbox_square-green checked\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green hover\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(job.getAttribute('class') == \"icheckbox_square-green hover\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green checked\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction workTimeValue(time){\r\n");
      out.write("\t\t$(\"#offerUserWorktime\").val(time);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\" onload=\"init()\">\r\n");
      out.write("\t<form id=\"userInformationForm\" style=\"overflow-y:auto;\">\r\n");
      out.write("\t<div style=\"width:100%;height:55px;background: #000;padding-top:20px;padding-left:150px;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<div style=\"\"><img src=\"../img/U-Offerlogo.png\"></div>\r\n");
      out.write("\t\t<div class=\"dropdown\" style=\"margin-top:-50px;margin-left:400px;\">\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">面试邀请</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">我的简历</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;margin-left:400px;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">个人设置\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">退出\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<div style=\"width:600px;\">\r\n");
      out.write("\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textC\" style=\"padding-left:10px;padding-top:10px;padding-bottom:10px;width:25%;\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"circleA\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><font color=\"#00B38A\">&nbsp;&nbsp;基本信息 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"textC\" style=\"padding-left:10px;padding-top:10px;padding-bottom:10px;width:25%;\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"circleB\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><font color=\"#999999\">&nbsp;&nbsp;期望工作 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"textC\" style=\"padding-left:10px;padding-top:10px;padding-bottom:10px;width:25%;\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"circleB\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><font color=\"#999999\">&nbsp;&nbsp;个人经历 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td class=\"textC\" style=\"padding-left:10px;padding-top:10px;padding-bottom:10px;width:25%;\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><div class=\"circleB\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><font color=\"#999999\">&nbsp;&nbsp;调查问卷 </font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"background: #FFFFFF; width: 600px;padding-top:20px;padding-bottom:20px;\">\r\n");
      out.write("\t\t\t<center><font size=\"3\" color=\"#666666\">Hi,欢迎您的到来！让我们来认识一下吧。</font></center>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"height: 2px; width: 600px; background-color: #999999;\"></div>\r\n");
      out.write("\t\t<div style=\"background: #FFFFFF; width: 600px;\">\r\n");
      out.write("\t\t\t<br />\r\n");
      out.write("\t\t\t<table\r\n");
      out.write("\t\t\t\tstyle=\"border-collapse: separate; border-spacing: 10px; width: 100%; padding-left:30px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th class=\"textL\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\" color=\"#666666\">姓名*</font>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"offerUserName\" class=\"form-control\" style=\"width: 75% !important\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textL\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\" color=\"#666666\">性别*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"offerUserSex\" id=\"offerUserSex\"/>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"setSexValue(1)\" data-toggle=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #00B38A !important;background-color: #FFF !important; border-color: #00B38A !important; width: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t男</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"setSexValue(0)\" data-toggle=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"color: #00B38A !important;background-color: #FFF !important; border-color: #00B38A !important; width: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t\t女</button>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textL\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\" color=\"#666666\">工作年限*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textL\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\" style=\"margin-left:-10px !important;width: 90% !important\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown\" style=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"offerUserWorktime\" id=\"offerUserWorktime\" class=\"form-control\" style=\"width: 80% !important\">\r\n");
      out.write("\t\t\t\t\t\t\t    <button type=\"button\" style=\"height:34px !important;background-color:#E6E6E6;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t        <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t\t\t    <ul class=\"dropdown-menu\" role=\"menu\" aria-labelledby=\"dropdownMenu1\" style=\"width: 90% !important\" id=\"offerUserWorktime\">\r\n");
      out.write("\t\t\t\t\t\t\t        <li role=\"presentation\">\r\n");
      out.write("\t\t\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick='workTimeValue(\"1年\")'><font color=\"#000\">1年</font></a>\r\n");
      out.write("\t\t\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick='workTimeValue(\"一至三年\")'><font color=\"#000\">一至三年</font></a>\r\n");
      out.write("\t\t\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick='workTimeValue(\"三至五年\")'><font color=\"#000\">三至五年</font></a>\r\n");
      out.write("\t\t\t\t\t\t\t            <a role=\"menuitem\" tabindex=\"-1\" href=\"#\" onclick='workTimeValue(\"五年以上\")'><font color=\"#000\">五年以上</font></a>\r\n");
      out.write("\t\t\t\t\t\t\t        </li>\r\n");
      out.write("\t\t\t\t\t\t\t    </ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textL\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\" color=\"#666666\">您期望的工作岗位是？（最多选择两项）*</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textR\" style=\"padding-top:10px;padding-bottom:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icheckbox_square-green hover\" onclick=\"jobId(this)\">\r\n");
      out.write("\t\t\t\t\t\t            \t<input tabindex=\"2\" type=\"checkbox\" style=\"opacity:0;\" class=\"jobId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textL\"><font size=\"2\">Java工程师</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textR\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icheckbox_square-green hover\" onclick=\"jobId(this)\">\r\n");
      out.write("\t\t\t\t\t\t            \t<input tabindex=\"2\" type=\"checkbox\" style=\"opacity:0;\" class=\"jobId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textL\"><font size=\"2\">Java工程师</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textR\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icheckbox_square-green hover\" onclick=\"jobId(this)\">\r\n");
      out.write("\t\t\t\t\t\t            \t<input tabindex=\"2\" type=\"checkbox\" style=\"opacity:0;\" class=\"jobId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textL\"><font size=\"2\">Java工程师</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textR\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"icheckbox_square-green hover\" onclick=\"jobId(this)\">\r\n");
      out.write("\t\t\t\t\t\t            \t<input tabindex=\"2\" type=\"checkbox\" style=\"opacity:0;\" class=\"jobId\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td class=\"textL\"><font size=\"2\">Java工程师</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"textL\" colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<font size=\"1\" color=\"#666666\">您擅长哪些工作技能？（请用逗号分隔你的技能特长）</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"name\" class=\"form-control\" style=\"width: 75% !important\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"10px\"/>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"height: 2px; width: 600px; background-color: #999999;\"></div>\r\n");
      out.write("\t\t<div style=\"width: 600px; background-color: #FFF;\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"validateCode()\" data-toggle=\"button\"\r\n");
      out.write("\t\t\t\tstyle=\"color: #FFF !important;background-color: #00B38A !important; border-color: #00B38A !important; width: 200px;\">\r\n");
      out.write("\t\t\t\t下一步</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
