/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-02-23 01:54:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class maininterview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1486536911388L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../skins/all.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script src=\"../js/jquery.icheck.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.js\"></script>\r\n");
      out.write("<script src=\"../js/custom.min.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar code;\r\n");
      out.write("\tfunction getTran(ret) {\r\n");
      out.write("\t\tvar trans1 = document.getElementById('transparent1');\r\n");
      out.write("\t\tvar trans2 = document.getElementById('transparent2');\r\n");
      out.write("\t\tif (ret == '1') {\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (ret == '2') {\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeRemeber() {\r\n");
      out.write("\t\tvar remeberId = document.getElementById('remeberId').value;\r\n");
      out.write("\t\tif (remeberId == '1') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/cha.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '2';\r\n");
      out.write("\t\t} else if (remeberId == '2') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/gou.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '1';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tgetTran('1');\r\n");
      out.write("\t\tvar regit = document.getElementById('regit');\r\n");
      out.write("\t\tregit.focus();\r\n");
      out.write("\t\tvar b = document.getElementById('button1');\r\n");
      out.write("\t\tb.focus();\r\n");
      out.write("\t\tcode = createValidateCode('vCode2');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validateCode() {\r\n");
      out.write("\t\tvar ispass = code.verify(document.getElementById(\"inputCode\").value);\r\n");
      out.write("\t\tif (ispass) {\r\n");
      out.write("\t\t\tajaxSumbit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#999999\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#000\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor3(der){\r\n");
      out.write("\t\tder.style.background=\"#00B38A\";\r\n");
      out.write("\t\tder.style.color=\"#FFF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor4(der){\r\n");
      out.write("\t\tder.style.background=\"#FFF\";\r\n");
      out.write("\t\tder.style.color=\"#666666\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction jobId(job){\r\n");
      out.write("\t\tif(job.getAttribute('class') == \"icheckbox_square-green checked\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green hover\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(job.getAttribute('class') == \"icheckbox_square-green hover\"){\r\n");
      out.write("\t\t\tjob.setAttribute(\"class\",\"icheckbox_square-green checked\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\">\r\n");
      out.write("\t<div style=\"width:100%;height:55px;background: #000;padding-top:20px;padding-left:150px;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<div style=\"\"><img src=\"../img/U-Offerlogo.png\"></div>\r\n");
      out.write("\t\t<div class=\"dropdown\" style=\"margin-top:-50px;margin-left:400px;\">\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">面试邀请</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">我的简历</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;margin-left:400px;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">个人设置\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">退出\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"5%\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td rowspan=\"10\" valign=\"top\" width=\"250px\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" style=\"background:#FFF\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\">新的面试邀请(1)</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\"><font size=\"3\">待沟通(1)</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\"><font size=\"3\">待安排面试(1)</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\"><font size=\"3\">已安排面试(1)</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\"><font size=\"3\">面试结果(1)</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textL\" style=\"cursor:pointer;padding-top:15px;padding-bottom:15px;padding-left:60px;padding-right:20px;\" onmouseover=\"changeColor3(this)\" onmouseout=\"changeColor4(this)\"><font size=\"3\">已拒绝面试邀请(1)</font></td></tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"10px\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td class=\"textL\" width=\"250px\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<iframe height=\"550px\" src=\"maininterview_object.jsp\" width=\"250px\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0px\" marginwidth=\"0px\"></iframe>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td rowspan=\"10\" class=\"textL\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<iframe height=\"550px\" src=\"maininterview_object_view.jsp\" width=\"560px\" scrolling=\"auto\" frameborder=\"0\" marginheight=\"0px\" marginwidth=\"0px\"></iframe>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
