/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2017-02-07 07:52:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.util.*;

public final class mainresume_005fadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/common/header.jsp", Long.valueOf(1485738599553L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>My JSP 'index.jsp' starting page</title>\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("<link href=\"../css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"../css/base.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<script src=\"../js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/ajaxSubmit.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"../js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"../js/Carousel.js\"></script>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction upload() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"register/firm.do\", // 自行按需配置好完整的url，包括ip和端口号  \r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdatatype : \"text\",\r\n");
      out.write("\t\t\tdata : JSON.stringify($(\"#form1\").serializeObject()),\r\n");
      out.write("\t\t\tcontentType : \"application/json\",\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tvar code;\r\n");
      out.write("\tfunction getTran(ret) {\r\n");
      out.write("\t\tvar trans1 = document.getElementById('transparent1');\r\n");
      out.write("\t\tvar trans2 = document.getElementById('transparent2');\r\n");
      out.write("\t\tif (ret == '1') {\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (ret == '2') {\r\n");
      out.write("\t\t\ttrans2.setAttribute(\"class\", \"triangle-up\");\r\n");
      out.write("\t\t\ttrans1.setAttribute(\"class\", \"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeRemeber() {\r\n");
      out.write("\t\tvar remeberId = document.getElementById('remeberId').value;\r\n");
      out.write("\t\tif (remeberId == '1') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/cha.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"17px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '2';\r\n");
      out.write("\t\t} else if (remeberId == '2') {\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').src = \"../img/gou.png\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.width = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeber').style.height = \"20px\";\r\n");
      out.write("\t\t\tdocument.getElementById('remeberId').value = '1';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction init() {\r\n");
      out.write("\t\tgetTran('1');\r\n");
      out.write("\t\tvar regit = document.getElementById('regit');\r\n");
      out.write("\t\tregit.focus();\r\n");
      out.write("\t\tvar b = document.getElementById('button1');\r\n");
      out.write("\t\tb.focus();\r\n");
      out.write("\t\tcode = createValidateCode('vCode2');\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validateCode() {\r\n");
      out.write("\t\tvar ispass = code.verify(document.getElementById(\"inputCode\").value);\r\n");
      out.write("\t\tif (ispass) {\r\n");
      out.write("\t\t\tajaxSumbit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor1(der){\r\n");
      out.write("\t\tder.style.background=\"#999999\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changeColor2(der){\r\n");
      out.write("\t\tder.style.background=\"#000\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body bgcolor=\"#F4F9F9\" onload=\"init()\">\r\n");
      out.write("\t<div style=\"width:100%;height:55px;background: #000;padding-top:20px;padding-left:150px;position:absolute;top:expression(documentElement.scrollTop + 'px');position:fixed;z-index:9999;\">\r\n");
      out.write("\t\t<div style=\"\"><img src=\"../img/U-Offerlogo.png\"></div>\r\n");
      out.write("\t\t<div class=\"dropdown\" style=\"margin-top:-50px;margin-left:400px;\">\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu3\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">面试邀请</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu2\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">\r\n");
      out.write("\t\t    \t<font size=\"3\">我的简历</font>\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;margin-left:400px;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">个人设置\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t    <button type=\"button\" style=\"height:59px !important;width:80px !important;color:#FFF;background-color:#000;\" class=\"btn dropdown-toggle\" id=\"dropdownMenu4\" data-toggle=\"dropdown\" onmouseover=\"changeColor1(this)\" onmouseout=\"changeColor2(this)\">退出\r\n");
      out.write("\t\t    </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<table width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"10%\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td rowspan=\"10\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table width=\"100%\" style=\"background:#FFF\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td width=\"100%\" class=\"textC\" style=\"padding-top:10px;padding-left:10px;padding-bottom:10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"3\" color=\"#999999\">简历完成度：</font>\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"4\" color=\"#00B38A\">70%</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td height=\"1px\" bgcolor=\"#999999\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><img/><font size=\"3\" color=\"#00B38A\">个人信息</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">个人技能</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">工作经历</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">教育经历</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">项目经历</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">个人描述</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">个人作品</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr><td class=\"textC\" style=\"padding-top:10px;padding-left:10px;\"><font size=\"3\" color=\"#00B38A\">隐私保护</font></td></tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"textC\">\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"background: #FFFFFF; width: 250px;padding-top:20px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 250px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t   \t\t\t<font size=\"3\">预览下载简历</font>\r\n");
      out.write("\t\t\t\t\t\t   \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr height=\"20px\"/>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"30px\" rowspan=\"10\"/>\r\n");
      out.write("\t\t\t<td class=\"textL\">\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"5\" width=\"100px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"90px\"/>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td />\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"3\" style=\"font-weight:bold;\">Y小姐</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"1\">女 28岁 现居住北京|C/C++工程师算法工程师|期望年薪34万</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"50px\">\r\n");
      out.write("\t\t\t\t\t\t\t<td><font size=\"1\">通信工程，太原理工大学</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><font color=\"#00B38A\" size=\"1\">候选人同意面试邀请后方能查看联系方式</font></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td/>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr height=\"20px\"/>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">关于Y小姐</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">技能</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-group btn-group-lg\" style=\"margin-left:30px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 100px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<font size=\"2\">不感兴趣</font>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-group btn-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 100px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<font size=\"2\">不感兴趣</font>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-group btn-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 100px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<font size=\"2\">不感兴趣</font>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-group btn-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 100px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<font size=\"2\">不感兴趣</font>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"btn-group btn-group-lg\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t<button type=\"button\" class=\"btn btn-default\" style=\"width: 100px;height:40px;\">\r\n");
      out.write("\t\t\t\t\t\t    \t\t\t<font size=\"2\">不感兴趣</font>\r\n");
      out.write("\t\t\t\t\t\t    \t\t</button>\r\n");
      out.write("\t\t\t\t\t\t    \t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">工作经历</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">教育经历</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">个人描述</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><font size=\"1\" color=\"#666666\">目前</font></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">个人作品</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<div style=\"background: #FFFFFF; width: 750px; margin-top:10px;padding-top:30px;padding-left:20px;\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;margin-left:30px;\">隐私保护</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p></p>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"20%\" class=\"textC\" valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<font size=\"2\" color=\"#00B38A\">编辑</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
