/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-02-23 01:54:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class maininterview_005fobject_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("</head>\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("\tfunction changColor1(di) {\r\n");
      out.write("\t\tdi.getElementsByTagName(\"table\")[0].style.backgroundColor=\"#DDDDDD\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction changColor2(di) {\r\n");
      out.write("\t\tdi.getElementsByTagName(\"table\")[0].style.backgroundColor=\"#FFFFFF\";\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction getMessage(di) {\r\n");
      out.write("\t\tdi.getElementsByTagName(\"table\")[0].style.backgroundColor=\"#DDDDDD\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("\t.getColor{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t\tborder:1px #999999 solid;\r\n");
      out.write("\t}\r\n");
      out.write("\t.getTdColor{\r\n");
      out.write("\t\tbackground-color:#00B38A;\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.getTdColor:focus{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t.getTdColor:hover{\r\n");
      out.write("\t\tbackground-color:#FFF;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"getColor\" tabindex=\"0\" style=\"width:540px;\">\r\n");
      out.write("\t\t<table style=\" width: 540px;padding-top:5px;padding-left:10px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<font size=\"3\" style=\"font-weight:bold;\">一心里</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td rowspan=\"5\" width=\"150px\" style=\"padding-top:5px;padding-left:10px;padding-bottom:5px;padding-right:10px;\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"140px\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\"><font size=\"1\">广州</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\"><font size=\"1\" color=\"#999999\">职位：</font><font size=\"1\">java</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\"><font size=\"1\" color=\"#999999\">薪酬：</font><font size=\"1\">java</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\"><font size=\"1\" color=\"#999999\">期权/股权：</font><font size=\"1\">java</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\"><font size=\"1\" color=\"#999999\">公司简介：</font><font size=\"1\">java</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"20px\">\r\n");
      out.write("\t\t\t\t<td class=\"textL\" colspan=\"2\"><font size=\"1\">java(HR)5分钟前发送</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"getColor\" style=\"width:540px;\">\r\n");
      out.write("\t\t<table style=\" width: 100%;padding-top:25px;padding-left:20px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:90px !important;\" class=\"textL\">\r\n");
      out.write("\t\t\t\t\t<img src=\"../img/changjinglu.jpg\" width=\"90px\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"textL\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\">jack</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"100px\" class=\"textC\">\r\n");
      out.write("\t\t\t\t\t<font size=\"1\" color=\"#00B38A\">2016-10-21</font>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"20px\">\r\n");
      out.write("\t\t\t\t<td class=\"textL\" colspan=\"3\" style=\"padding-right:20px;\"><font size=\"1\">java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送java(HR)5分钟前发送</font></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"width:540px;border:1px #999999 solid;\">\r\n");
      out.write("\t\t<table style=\"background:#00B38A;width:100%;cellpadding:0px;cellspacing:0px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"getTdColor\"><center>和他沟通</center></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><div class=\"getTdColor\"><center>同意面试邀请</center></div></td>\r\n");
      out.write("\t\t\t\t<td><div class=\"getTdColor\"><center>拒绝面试邀请</center></div></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"getColor\" style=\"width:540px;\">\r\n");
      out.write("\t\t<table style=\" width: 100%;padding-top:25px;padding-left:20px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td style=\"width:90px !important;\" class=\"textL\">\r\n");
      out.write("\t\t\t\t\t如果你对此邀请不满意，你可以拒绝企业邀请\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textL\">\r\n");
      out.write("\t\t\t\t\t<textarea placeholder=\"你好，感谢邀请，对贵公司的职位不感兴趣...\"></textarea>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"textC\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"validateCode()\" data-toggle=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"background-color: #00B38A !important; border-color: #00B38A !important; width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t提交</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
